In [1]:
import pandas as pd 
df = pd.read_csv("bill.csv")
df

     student name  rollno  marks percentage
0  Ritik Humagain      22   3000        88%
1  Rajat Adhikari      44   5500        50%

In [ ]:

df = pd.read_csv("Salary Data.csv")
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [ ]:
df.shape # To find the shape of the csv file

(375, 6)

In [5]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [6]:
df.head(10)

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
5,29.0,Male,Bachelor's,Marketing Analyst,2.0,55000.0
6,42.0,Female,Master's,Product Manager,12.0,120000.0
7,31.0,Male,Bachelor's,Sales Manager,4.0,80000.0
8,26.0,Female,Bachelor's,Marketing Coordinator,1.0,45000.0
9,38.0,Male,PhD,Senior Scientist,10.0,110000.0

In [8]:
df.tail()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [9]:
df.tail(10)

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
365,43.0,Male,Master's,Director of Marketing,18.0,170000.0
366,31.0,Female,Bachelor's,Junior Financial Analyst,3.0,50000.0
367,41.0,Male,Bachelor's,Senior Product Manager,14.0,150000.0
368,44.0,Female,PhD,Senior Data Engineer,16.0,160000.0
369,33.0,Male,Bachelor's,Junior Business Analyst,4.0,60000.0
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [20]:
df = pd.read_csv("Salary Data.csv",nrows = 6)
df

   Age  Gender Education Level          Job Title  Years of Experience  Salary
0   32    Male      Bachelor's  Software Engineer                    5   90000
1   28  Female        Master's       Data Analyst                    3   65000
2   45    Male             PhD     Senior Manager                   15  150000
3   36  Female      Bachelor's    Sales Associate                    7   60000
4   52    Male        Master's           Director                   20  200000
5   29    Male      Bachelor's  Marketing Analyst                    2   55000

In [ ]:
df[["Age","Gender","Salary"]]

df = pd.read_csv("Salary Data.csv",nrows = 6)
df

   Age  Gender  Salary
0   32    Male   90000
1   28  Female   65000
2   45    Male  150000
3   36  Female   60000
4   52    Male  200000
5   29    Male   55000

In [27]:
df = pd.read_csv("Salary Data.csv")
df.iloc[0:10:2]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
4,52.0,Male,Master's,Director,20.0,200000.0
6,42.0,Female,Master's,Product Manager,12.0,120000.0
8,26.0,Female,Bachelor's,Marketing Coordinator,1.0,45000.0

In [28]:
df.iloc[0:5,1:4]

   Gender Education Level          Job Title
0    Male      Bachelor's  Software Engineer
1  Female        Master's       Data Analyst
2    Male             PhD     Senior Manager
3  Female      Bachelor's    Sales Associate
4    Male        Master's           Director

In [33]:
#filter
df[df["Age"] > 50]

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
4,52.0,Male,Master's,Director,20.0,200000.0
19,51.0,Male,Bachelor's,Sales Director,22.0,180000.0
50,51.0,Female,Bachelor's,Customer Service Manager,22.0,130000.0
60,51.0,Female,Master's,Director of Operations,23.0,170000.0
83,52.0,Male,PhD,Chief Technology Officer,24.0,250000.0
93,52.0,Female,Master's,Senior Marketing Manager,25.0,170000.0
121,53.0,Male,Master's,Director of Marketing,25.0,180000.0
158,51.0,Female,PhD,Director of Human Resources,23.0,185000.0
229,51.0,Female,Master's,Director of Human Resources,21.0,190000.0

In [44]:
filter_data = df[(df["Education Level"] == "PhD")& (df["Age"] > 50)]
filter_data.to_csv("filter_data.csv")

In [ ]:
# Dict to dataframe
data = {
    "name": ["ram","shyam","hari"],
    "age":[34,55,6],
    "add":["kathmandu","bhaktapur","lalitpur"],

}
filter_data = pd.DataFrame(data)
filter_data



# filter_data.to_csv("filter_data.csv")

    name  age        add
0    ram   34  kathmandu
1  shyam   55  bhaktapur
2   hari    6   lalitpur